### ISSUE TITLE
404 

### ISSUE THREAD

**Issue by twentysixmoons** [open-austin/budgetparty-landing#6]
http://austinbudget.party/home

When I put that in my browser I get a 404. Any idea why? It's hard for me to go back to the home. 
<img width="1440" alt="screen shot 2017-06-30 at 5 39 22 pm" src="https://user-images.githubusercontent.com/10767430/27756201-2e026b9e-5dbb-11e7-98c5-51193c8b56f3.png">

**Comment by twentysixmoons** [comment]
@prestonp any ideas?

**Comment by mateoclarke** [comment]
I think this is because of React Router. To load the app, you have to go to austinbudget.party. Once you are there, you download all the js files including React Router's features and then you can get to austinbudget.party/home. 

So how to we add more routes within hosting via Github?

**Comment by twentysixmoons** [comment]
I don't think there is a problem here anymore.
